
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  datasource:
    url: "jdbc:sqlite:./db/library-data.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0
cds:
  data-source.auto-config.enabled: false